name = "Nefarious"
uuid = "2e8ee96f-164a-4f62-b0c6-68f6fb694f59"
authors = ["Stefan Karpinski <stefan@karpinski.org>"]
version = "0.1.0"

[deps]
JSON = "976bc2ab-e352-4e1b-90ff-fe19bada0106"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
